### ISSUE TITLE
Old customers don't have the account resource

### ISSUE THREAD

**Issue by rserna2010** [balanced/balanced-api#728]

**Comment by sophistry** [comment]
:+1:

**Comment by sophistry** [comment]
also, in the meantime... can we make a one-time request to have the account object provisioned to the marketplace account? - assuming it has not been added to the marketplace yet.

**Comment by mjallday** [comment]
@rserna2010 can you expand on what you mean?

**Comment by mahmoudimus** [comment]
@sophistry @rserna2010 what does "old customers" mean? what account resource are we referring to? what version of the API is this talking about?

**Comment by mjallday** [comment]
Closing, will reopen if more information is provided.

**Comment by sophistry** [comment]
So, is this issue re-opened? I would assume it affects multiple other customers...

**Comment by mahmoudimus** [comment]
@sophistry yup, will open for now. thx for reporting. investigating this and getting back to you.

**Comment by sophistry** [comment]
This data is from a test account BTW.

**Comment by kpowerinfinity** [comment]
+1 - tried on my test account as well and still see the issue.

**Comment by mjallday** [comment]
@sophistry that explains it. we did not backfill test marketplaces. going forward we recommend you create new test marketplaces rather than using old ones.

**Comment by sophistry** [comment]
Hi @mjallday - that doesn't sound quite right - and it makes me lose a certain amount of confidence in the API. I think this needs to be addressed by backfilling test accounts too.

**Comment by sophistry** [comment]
By the way, we've created new test accounts for local development, but you are saying that we have to throwaway all of our legacy data?

Actually, that won't work for us for one very big reason: we recently upgraded to the v1.1 API and one of the issues we've had to deal with is to make sure old API transactions (of which we have many on our staging and live servers) are handled correctly. There are multiple code paths required when handling refunds for example - the old API didn't require use of Events or polling, but the new API (with the Orders construct) does. 

For instance, a refund coming from an old API debit has to be paid out from a main escrow credit rather than a per-order credit.

If you force us to update away from our existing cache of old API transactions, we will have no way to test that these code paths still work until a live refund hits.

Please re-open and backfill +1

**Comment by sophistry** [comment]
Additionally, there should be a note in the API documentation - this took a few hours to arrive at and discuss over support@balancedpayments.com and this ticket - it should not be something devs are expected to stumble on and divine.

**Comment by mjallday** [comment]
@sophistry yes, i have backfilled this particular test marketplace, i was stating our general policy, apologies that that was not clear.

i appreciate what you're saying regarding migrating between revisions of the API. for that particular use case you can still create transactions that do not use orders and are therefore credited into the general balance for your marketplace rather than a balance associated to an order.

the issue if you continue using an old marketplace and relying on transactions created before you migrated is that eventually you will run out of these old transactions to test your refund logic against.

if you'd like some help setting up the flow i've suggested here then please jump into our IRC room and we can show you how to setup the marketplace with this information. 

i agree that this should be announced and we'll strive to do that going forward, thanks for your feedback :)

**Comment by sophistry** [comment]
Ok - Thank you for the reply. I see the accounts objects now on the test account I sent with this issue. 

This marketplace is not our staging marketplace though...

This is our staging marketplace - it would be nice to have the ability to test through our whole release process: TEST-MP4fky1d481RiIUHX2tgLjLW

Thanks!
